# Generated by Django 5.1.5 on 2025-01-22 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Ativo"),
                ),
                (
                    "classe",
                    models.CharField(
                        choices=[
                            ("Renda Fixa", "Renda Fixa"),
                            ("Renda Variável", "Renda Variável"),
                        ],
                        max_length=20,
                        verbose_name="Classe do Ativo",
                    ),
                ),
                (
                    "subclasse",
                    models.CharField(
                        choices=[
                            (
                                "Renda Fixa",
                                [
                                    ("CDB", "CDB"),
                                    ("Tesouro Direto", "Tesouro Direto"),
                                    ("Fundo de Renda Fixa", "Fundo de Renda Fixa"),
                                ],
                            ),
                            (
                                "Renda Variável",
                                [
                                    ("Ações", "Ações"),
                                    ("FII", "FII"),
                                    ("Criptomoeda", "Criptomoeda"),
                                    ("Fundos no Exterior", "Fundos no Exterior"),
                                ],
                            ),
                        ],
                        max_length=50,
                        verbose_name="Subclasse do Ativo",
                    ),
                ),
                ("banco", models.CharField(max_length=50, verbose_name="Banco")),
                (
                    "valor_inicial",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Valor Inicial"
                    ),
                ),
                ("data_aquisicao", models.DateField(verbose_name="Data de Aquisição")),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
    ]
