# Generated by Django 5.1.5 on 2025-01-23 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("investimentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operacao",
            options={"verbose_name": "Operação", "verbose_name_plural": "Operações"},
        ),
        migrations.AlterModelTable(
            name="operacao",
            table="operacoes",
        ),
    ]
