# Generated by Django 5.1.5 on 2025-01-22 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investimentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("compra", "Compra"),
                            ("venda", "Venda"),
                            ("atualizacao", "Atualização"),
                        ],
                        max_length=15,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=15)),
                ("data", models.DateField()),
                (
                    "ativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operacoes",
                        to="investimentos.ativo",
                    ),
                ),
            ],
        ),
    ]
