# Generated by Django 5.1.5 on 2025-02-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investimentos", "0003_alter_ativo_subclasse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ativo",
            name="observacoes",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Observações"
            ),
        ),
    ]
