# Generated by Django 5.1.5 on 2025-02-10 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investimentos", "0006_alter_ativo_subclasse"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentabilidadeHistorica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_referencia", models.DateField()),
                (
                    "rentabilidade_abs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "rentabilidade_perc",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_rentabilidade",
                        to="investimentos.ativo",
                    ),
                ),
            ],
            options={
                "ordering": ["data_referencia"],
                "unique_together": {("ativo", "data_referencia")},
            },
        ),
    ]
