# Generated by Django 5.1.5 on 2025-02-11 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("investimentos", "0007_rentabilidadehistorica"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RentabilidadeHistorica",
        ),
    ]
