# Generated by Django 5.1.5 on 2025-02-18 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investimentos", "0008_delete_rentabilidadehistorica"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValorAtivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "ativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valores",
                        to="investimentos.ativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "valor ativo",
                "verbose_name_plural": "valores ativos",
                "db_table": "valores_ativo",
            },
        ),
    ]
