# Generated by Django 5.1.5 on 2025-02-21 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investimentos", "0009_valorativo"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentabilidadeAtivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_referencia", models.DateField()),
                (
                    "rentabilidade_abs",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "rentabilidade_perc",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "ativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rentabilidades",
                        to="investimentos.ativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "rentabilidade ativo",
                "verbose_name_plural": "rentabilidades ativo",
                "db_table": "rentabilidade_ativo",
            },
        ),
    ]
